### PR TITLE
Enable Isaac Mission Dispatch and VDA5050 Connector to work together

### PR DESCRIPTION
**Pull request by nv-yuzho**

### CODE REVIEW

**Comment by leandropineda** [comment]
Thanks for your PR @nv-yuzho ! Changes looks good to me.

I was wondering why you changed the network mode to `host`. Are you using a Mission Dispatch service locally that connects to the containers?

**Comment by nv-yuzho** [comment]
> Thanks for your PR @nv-yuzho ! Changes looks good to me.
> 
> I was wondering why you changed the network mode to `host`. Are you using a Mission Dispatch service locally that connects to the containers?

Hi, @leandropineda! 
Yes, I'm testing everything locally for now. 
But if I didn't set the network to host, the [order1 example](https://github.com/inorbit-ai/vda5050_adapter_examples/blob/galactic-devel/vda5050_tb3_adapter/test/integration/order1.py) in this repo didn't seem to work either.

**Review by leandropineda — APPROVED** [review]

**Comment by leandropineda** [comment]
Now I see why, thanks for the fix. LGTM!

**Comment by nv-yuzho** [comment]
> Now I see why, thanks for the fix. LGTM!

No problem!

**Comment by nv-yuzho** [comment]
Could this PR be merged?

**Comment by leandropineda** [comment]
Yes, please go ahead and merge it

**Comment by nv-yuzho** [comment]
> Yes, please go ahead and merge it

I think I don't have the write access to get this merged.

**Comment by leandropineda** [comment]
Indeed, I'll merge it then.

**Comment by nv-yuzho** [comment]
Thank you!

**Comment by fmros** [comment]
Due to [this](https://github.com/inorbit-ai/vda5050_adapter_examples/commit/e074d434491e20897f3b5e736416f44e8cf9e2a2) commit it is not possible to run the Isaac Mission Dispatch together with this package, since the network_mode is not set to local_host in the docker-compose file. What do you think to leave the settings merged in this PR as a separate branch?

**Comment by leandropineda** [comment]
> Due to [this](https://github.com/inorbit-ai/vda5050_adapter_examples/commit/e074d434491e20897f3b5e736416f44e8cf9e2a2) commit it is not possible to run the Isaac Mission Dispatch together with this package, since the network_mode is not set to local_host in the docker-compose file. What do you think to leave the settings merged in this PR as a separate branch?

@fmros I generally try to avoid using `host` network mode unless strictly necessary. Also, we want to avoid having additional branches so we keep maintenance effort as low as possible.

We can make containers spawned by both docker compose files see each other by using the `networks` construct. For doing so we'd need to do two things:

1. Modify the docker compose file on this repository to create a named `bridge` network
```yaml
...
networks:
  vda5050-adapter-examples:
    driver: bridge
```

2. Modify the Isaac Mission Dispatch docker compose file to use the same network:
```yaml
...
networks:
  front_vda5050-adapter-examples:
    external: true
```

The Mission Dispatch docker compose also creates an MQTT container which might be confusing or error prone. Perhaps you could add a separate docker compose file that links to the `vda5050-adapter-examples` network without the MQTT instance. This way we can integrate both projects seamlessly while keeping the current Mission Dispatch compose file unchanged. WDYT?

**Comment by nv-yuzho** [comment]
> > Due to [this](https://github.com/inorbit-ai/vda5050_adapter_examples/commit/e074d434491e20897f3b5e736416f44e8cf9e2a2) commit it is not possible to run the Isaac Mission Dispatch together with this package, since the network_mode is not set to local_host in the docker-compose file. What do you think to leave the settings merged in this PR as a separate branch?
> 
> @fmros I generally try to avoid using `host` network mode unless strictly necessary. Also, we want to avoid having additional branches so we keep maintenance effort as low as possible.
> 
> We can make containers spawned by both docker compose files see each other by using the `networks` construct. For doing so we'd need to do two things:
> 
> 1. Modify the docker compose file on this repository to create a named `bridge` network
> 
> ```yaml
> ...
> networks:
>   vda5050-adapter-examples:
>     driver: bridge
> ```
> 
> 2. Modify the Isaac Mission Dispatch docker compose file to use the same network:
> 
> ```yaml
> ...
> networks:
>   front_vda5050-adapter-examples:
>     external: true
> ```
> 
> The Mission Dispatch docker compose also creates an MQTT container which might be confusing or error prone. Perhaps you could add a separate docker compose file that links to the `vda5050-adapter-examples` network without the MQTT instance. This way we can integrate both projects seamlessly while keeping the current Mission Dispatch compose file unchanged. WDYT?

Yeah, I think the networks construct is a better solution! We will make the change on the Mission Dispatch side and test it out with the new changes you will make. Thank you. @leandropineda

**Pull request merged**
